spring:
  application:
    name: product-service
 cloud:
   rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
   stream:
    bindings:
      PRODUCT_QUEUE2:
        group: product

server:
  port: 9010  
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

boy:
  name: 熏悟空
  age: 600
